@host = http://localhost:3000
@urlUsers = /api/user

####################################
############### USER ###############
####################################

### GET ALL USERS
GET {{host}}{{urlUsers}}